name = "EmpymodWrapper"
uuid = "d47a47e7-57f3-4773-b84f-8dc5c83b4829"
authors = ["Ralph-Uwe Börner <rub@geophysik.tu-freiberg.de>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
